### ISSUE TITLE
Get the default (first) remote

### ISSUE THREAD

**Issue by vindarel** [rejeep/git.el#5]
For my app, I want to know if we're using github or gitlab (or another), so I try to get what is the "default remote" of this repo.

I first thought I'd pick the first result of the `git remote` command (and assume it's very probably the right thing), but it doesn't respect the order in which they appear in our git config file, the result is sorted a-z.

I could pick the result of `git config.master.remote`, but some repos, including mines, do have a master branch which isn't referenced inside the git config file, so this command doesn't work !

Do you know a clean way to get that information ?

There is `git branch -vv` whose result is to parse.

I went with scanning the config file and extracting the information from the first "[remote "name to get"]" section I encounter.

I thought git.el would help but it doesn't. I'd be glad to PR the following, what do you think ?

```
(defun git-first-remote ()
  "Get the first remote name found in git config file."
  (let* ((first-remote
          (with-temp-buffer
            (insert-file-contents (concat (projectile-project-root) ".git/config"))
            (if (search-forward "[remote \"")
                (progn
                  (buffer-substring-no-properties (line-beginning-position) (line-end-position))))))
         (first-remote (car (cdr (s-split " " first-remote))))
         (first-remote (s-replace "\"" "" first-remote))
         (first-remote (s-chop-suffix "]" first-remote)))
    first-remote))
```

(what about the projectile dependency for instance)

Regards

**Comment by rejeep** [comment]
I am certainly not an expert on Git, so I think stackoverflow would be a better place for this question. If you come up with something that might fit in this lib, please get back with a PR.
