### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by jgarte** [rejeep/git.el#8]
Hi,

Is this project still active/up to date?

**Comment by rejeep** [comment]
No/no 🙂

**Comment by jgarte** [comment]
@rejeep I think this library would still be useful today for creating eshell commands that do stuff with git:

https://howardism.org/Technical/Emacs/eshell-why.html

I prefer to not [call-process](https://github.com/rejeep/git.el/blob/a3396a7027a7d986598c6a2d6d5599bac918f3da/git.el#L69) myself but just use your wrappers.

Should we give `eshell` and `git.el` a second chance as Howard's article suggests?

WDYT

**Comment by jgarte** [comment]
I like that you don't wrap the subcommands directly but are arguments to `git-run`:

```lisp
(git-run "branch")
(git-run "commit")
(git-run "init")
(git-run "clone")
;; etc.
```
